name: Githubworkflow
on: push
env:
  DbName: TestDB
  DbUser: tester
  DbPassword: tester
jobs:
  runs_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Start Mysql Service
        run: |
          sudo /etc/init.d/mysql start
          # Create user and grant privileges
          sudo mysql -e "CREATE USER IF NOT EXISTS '${{ env.DbUser }}'@'localhost' IDENTIFIED BY '${{ env.DbPassword }}';" -uroot -p'root'
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO '${{ env.DbUser }}'@'localhost' WITH GRANT OPTION;" -uroot -p'root'
          sudo mysql -e "CREATE DATABASE ${{ env.DbName }};" -u${{ env.DbUser }} -p${{ env.DbPassword }}

      - name: Checkout from the Repository
        uses: actions/checkout@v2
      - name: Set Up Go Lang
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: Run Linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run Test Cases
        run: go test
            

