name: Githubworkflow
on: push
env:
  DbName: TestDB
  DbUser: dbhelper
  DbPassword: dbw0rk3r
jobs:
  runs_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Start Mysql Service
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'ALTER USER "${{ env.DbUser }}"@"localhost" IDENTIFIED BY "${{ env.DbPassword }}";' -uroot -proot
          sudo mysql -e "CREATE DATABASE ${{ env.DbName }};" -u{{env.DbUser}} -p{{env.DbPassword}}

      - name: Checkout from the Repository
        uses: actions/checkout@v2
      - name: Set Up Go Lang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run Linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run Test Cases
        run: go test
            

